standard_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_to_its_part_1
    - arm_1_to_arm_2
    - arm_2_to_arm_3
    - arm_3_to_arm_4
    - arm_4_to_arm_5
    - arm_5_to_arm_6
    - arm_6_to_end_effector
  gains:
    base_to_its_part_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_1_to_arm_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_2_to_arm_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_3_to_arm_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_4_to_arm_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_5_to_arm_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_6_to_end_effector:
      p: 100
      d: 1
      i: 1
      i_clamp: 1