controller_list:
  - name: standard_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_to_its_part_1
      - arm_1_to_arm_2
      - arm_2_to_arm_3
      - arm_3_to_arm_4
      - arm_4_to_arm_5
      - arm_5_to_arm_6
      - arm_6_to_end_effector